### ISSUE TITLE
[Analyse] Amazing Forms add to documentation

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#48]
## Expected Behavior
We would like to integrate Amazing Forms with Google recommendations. 

Link to the article: https://developers.google.com/web/fundamentals/design-and-ux/input/forms/

## Tasks:
* [ ] check all types of inputs (email, phone, password)
* [ ] integrate autocomplete option for input
* [ ] capture default browser validation and show with tooltip
* [ ] change a documentation (table + screenshot + short example)

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)|https://github.com/awes-io/issues]
