### ISSUE TITLE
Awes-SPA: Improvements & Bug fixing

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#76]
**Tasks:**
- [ ] Improve: SPA loading progress bar. Example: http://ricostacruz.com/nprogress/
- [ ] Integrate to documentation of Awes.io
- [ ] Bugfixing 
- [ ] In Awes-SPA documentation found a typo: `data-awes-container` -> `data-awes-spa-container`
- [ ] Add possibility to disable SPA from config

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)
